services:
  - type: web
    name: notification-campus
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: notificationdb
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: notificationdb
    databaseName: notifications
    user: notifuser
    plan: free
